CREATE SEQUENCE SEQ_ID_TIPO_CLIENTE
START WITH 1
INCREMENT BY 1;

CREATE TABLE TBL_TIPO_CLIENTE (
    idTipoCliente INT PRIMARY KEY DEFAULT nextval('SEQ_ID_TIPO_CLIENTE'),
    nombre VARCHAR(50) NOT NULL UNIQUE,
    condiciones VARCHAR(50) NOT NULL,
    subTipoCliente VARCHAR(50) NOT NULL
);