CREATE SEQUENCE SEQ_ID_ROLES
START WITH 1
INCREMENT BY 1
NO MINVALUE
NO MAXVALUE
CACHE 1;

CREATE TABLE TBL_ROLES (
    idRoles INT PRIMARY KEY DEFAULT nextval('SEQ_ID_ROLES'),
    nombre VARCHAR(50) NOT NULL UNIQUE,
    descripcion VARCHAR(255)
)