CREATE SEQUENCE SEQ_ID_PROMOCION
START WITH 1
INCREMENT BY 1
NO MINVALUE
NO MAXVALUE
CACHE 1;

CREATE TABLE Novedades (
    id_noticia INT PRIMARY KEY DEFAULT nextval('SEQ_ID_PROVEEDOR'),
    titulo VARCHAR(150) NOT NULL,
    contenido TEXT NOT NULL,
    fecha_publicacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    imagen VARCHAR(255),
    url VARCHAR(255),
    seccion VARCHAR(100)
);
